#! /usr/bin/env python3

"""
As I run things in venv for packages as well as want to be able to run this
from aoc bench, I use this launcher. Altough it should probably be located in
libs together with aoc-runner

TOOD: move it there
"""

import os
import subprocess
import sys
from pathlib import Path


def find_upstream_directory(target_dir):
    current_dir = os.getcwd()
    while True:
        if os.path.basename(current_dir) == target_dir:
            return current_dir
        parent_dir = os.path.dirname(current_dir)
        if parent_dir == current_dir:  # Reached root directory
            return None
        current_dir = parent_dir


def find_venv_path():
    venv_path = find_upstream_directory("build") + "/venv"
    if not os.path.exists(venv_path):
        print(f"Virtual environment not found in {venv_path}")
        sys.exit(1)
    return venv_path


def run_script_in_venv(target_path):
    venv_path = find_venv_path()

    venv_python = os.path.join(venv_path, "bin", "python")
    if not os.path.exists(venv_python):
        print(f"venv python not found in {venv_python}")
        sys.exit(2)

    # Setup the path s.t. scripts can import libraries
    env = os.environ.copy()
    env["PYTHONPATH"] = env.get("PYTHONPATH", "") + ":" + str(Path(__file__).resolve().parents[4])

    # TODO: Setup so that we exit with the return value of the subprocess
    subprocess.run([venv_python, target_path] + sys.argv[1:], env=env)

    return 0


if __name__ == "__main__":
    sys.exit(run_script_in_venv("solve.py"))
